# Generated by Django 4.2.6 on 2023-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
